### ISSUE TITLE
Network Info - Scope change and overlap with DeviceStatus API?

### ISSUE THREAD

**Issue by hdamker** [camaraproject/ConnectivityInsights#48]
**Problem description**

Within PR #40 there is beside a lot of other changes a new API "code/API_definitions/network-info.yaml" included.

This API seems to be 
a) not covered by the current scope of the Sub Project:

> - define intents in the form of policy thresholds for QoS metrics against the device and the application service. The API service will alert the consumers if and when the policy has breached.
> - NOTE: The scope of this API family should be limited (at least at a first stage) to 4G and 5G.

b) has a significant overlap with current discussion within DeviceStatus about the same functionality:

**Expected action**

Scope changes should be discussed with an issue in the API Backlog group. That allows also to identify potential overlaps and needs of scope overlap resolutions.
In addition the Sub Projects Connectivity Insights and DeviceStatus should discuss the scopes of their APIs with each other to avoid overlap and double work.

**Additional context**

**Comment by hdamker** [comment]
See also my comment within DeviceStatus: https://github.com/camaraproject/DeviceStatus/issues/143#issuecomment-2180573172

**Comment by maheshc01** [comment]
I had an opportunity to clarify this during today's TSC call as well but adding all the information here for everyone's benefit.

@Kevsy proposed the new features here as part of connectivity insights to provide developers with information on network connection details. this feature was discussed and debated if connectivity insights is the right place for it.
When put to vote, the majority on the call voiced their support for moving this capability out of connectivity insights and called out that it might be a better fit in device status.

following the discussion, 2 steps were decided as next actions:
1. separate the API from the core connectivity-insight.yaml and have a separate yaml so that we are not loosing out on the efforts put in to create the API spec and can be easily moved when a new home is found(done as part of #40)
2. bring this up in TSC call for deciding the right place for these capabilities.

Action for step 2 is with @Kevsy and i believe it is yet to be planned. @Kevsy, I miss alternate TSC calls due to my US timezone. Please share if there was any specific information which might have been discussed but i have missed.

**Comment by Kevsy** [comment]
Hi @hdamker - I'm happy to raise this in API Backlog, I can see 3 options:

1- Scope Enhancement for Connectivity Insights
2- Scope Enhancement for Device Status
3- New API Proposal for 'Network Information'

I can do (1), knowing that if it is accepted then the preferred realization may be agreed to be (2) or (3).  Is that OK?

**Comment by NoelWirzius** [comment]
Hey @Kevsy @hdamker @maheshc01 

I would recommend going with option 2. The proposal in Device Status focuses on the Network Connection Status of the device. Currently, we already have the Connection Status in Device Status, and we have agreed there not to add this to the API in order to keep it separate. This allows developers to decide which specific details of information they need. I would choose Device Status wg over Connectivity Insight wg because the Working Groups' directions suggest that  Connectivity Insight is more focused on general network information, while Device Status is more about device-specific information. 

Regardless of the final decision, I recommend considering scope enhancements for Device Status for the other endpoints/APIs as well. Some information, such as roaming, doesn't have much to do with the connection standard.

@Kevsy i would suggest we raise a general issue in API Backlog with your three options and trying to find a solution there and in best finding the right "split" between both APIs. 

Happy to discuss this

**Comment by Kevsy** [comment]
Hey @NoelWirzius - thanks, I've now created [API Backlog 61](https://github.com/camaraproject/APIBacklog/issues/61) accordingly.

**Comment by maheshc01** [comment]
PR #53  with the fix has been merged.
