### ISSUE TITLE
Introduce application server object in /insights and /insights/subscriptions

### ISSUE THREAD

**Issue by maheshc01** [camaraproject/ConnectivityInsights#54]
**Problem description**
Over the course of updates application server object was missed in the API request.

**Possible evolution**
re introducing application server object which will include ipv4 and ipv6 of the application instance.

**Alternative solution**

**Additional context**

**Comment by Kevsy** [comment]
Hi @maheshc01 - @emtwalt raised this topic on the [call 5th June](https://wiki.camaraproject.org/display/CAM/2024-06-05+-+sp-connectivity-minutes)

The suggestion was that there can be some value to the network knowing the identity of the application: for example, if the operator has an AMF rule for a given application, or even a peering point,  then the network can include that fact in its calculation of predicted network quality. It seems feasible that the application endpoint IP address can be used to lookup any AMF rules/peering points.

But, **I think if should be optional** - because if the application is not hosted on a predictable link, but simply on the 'best effort' Internet, then the operator will be forced to make a (not very accurate) calculation of (1) which route and (2) quality along that 'best effort' route. Which is a complex estimate to make given there will be no probes etc. on that route....so I can see operators ignoring that part for any non-AMF/peering apps.

**Comment by Kevsy** [comment]
> But i dont see making application server optional as a solution to it. Rather than developers taking a call on when would providing application server really help vs not, we can keep it simple for the developer to always provide the application server and the operator will use the information to make the calculation to their best of their ability.

Yeah that's a fair point  -  then the documentation can state that 'where the operator can use this info as part of its calculation it will'.

One thought though: the application server endpoint IP address may differ between territories (e.g. CDN)  or even networks in the same territories (e.g. for edge networks). So we need to consider how best to simplify that for the developer...

**Comment by maheshc01** [comment]
Hi @Kevsy i have added the following note in the "Application Server" description. "The Operator will use this information to calculate the end to end network performance in scenarios where its feasible."
Please reword if you think its not conveying the right message.

Also i have update the spec to use "applicationServer" and  "applicationServerPorts" objects to match with what is used in QoD API spec. i think the best current approach to keep is simple is , maintain the same definitions across the APIs which is where we are now. For future improvements we can propose updates to commonalities working group such that the same schema is used across the APIs.

**Comment by Kevsy** [comment]
Fixed in #55
