### ISSUE TITLE
API basepath should be human-readable

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/ConnectivityInsights#6]
**Problem description** 
_Updated following discussion below_
~~The mailing list three-letter acronym for Connectivity Insights is`coi` but the API's v0.1.0 basePath is `cni`~~
The v0.1.0 `basepath` is `coi` which is not human-readable 

**Expected behaviour**
~~Change the basepath from `cni` to `coi`~~
Change the basepath from `cni` to `connectivity-insights` per API Design Guidelines

**Alternative solution**
none

**Additional context**
none

**Comment by hdamker** [comment]
@Kevsy 

The mailing list acronym is a more less randomly chosen three letter combination. Please don't use that as basePath for your API. In fact there is only one API (qod) which has this coincidence (and that maybe due to the early times it started in CAMARA).

You should rather avoid an acronym or short name here, but follow all other APIs, and use something like `connectivity-insight` (or any other API name you will finally decide on). It should be human readable. Look on examples like `device-status`, `carrier-billing`, `number-verification`, etc.

**Comment by Kevsy** [comment]
Thanks @hdamker  - per my PR comment, any idea if that was discussed to be included in the API design guidelines? Would be good to have it clarified.

**Comment by hdamker** [comment]
The guidelines is quite clear:

> URI with lowercase and hyphens. URIs must be "human readable" to facilitate identification of the offered resources. Lowercase words and hyphenation (kebab-case) help achieve this best practice. For example: /customer-segments

Neither `coi`nor `cni` is "human readable".

**Comment by Kevsy** [comment]
Got it, thanks. My mistake!

**Comment by Kevsy** [comment]
OK changed issue title, issue description to reflect outcome of discussion above, and committed the human-readable basepath to PR #7

**Comment by Kevsy** [comment]
Fixed in #15
