### ISSUE TITLE
fix: reuse application-profile schema

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/ConnectivityInsights#79]
**Problem description**

Current model does not lend itself to reuse

**Expected behavior**

L50 - Consider to define a schema like CreateApplicationProfile which contains today only NetworkQualityThresholds but can be extended with further optional fields (see also below).

**Alternative solution**

**Additional context**

**Comment by hdamker** [comment]
Just for clarification:
The schema for the resource is already there with `ApplicationProfile`, which will be used e.g. in responses. `CreateApplicationProfile` would be just the structure with input parameters for the creation of an application profile resources (e.g. leaving the id out). Potentially a subset of the fields within `ApplicationProfile`.

**Comment by maheshc01** [comment]
based on general TSC guidelines i have refrained from introducing additional optional resources as of now.
As we start expanding the scope of application profile we this will have to be revisited on what would be the best way to handle this. For now as the utilization is only in connectivity insights, i have kept the scope narrow to use only network thresholds and match it to reuse QoD standards.

**Comment by hdamker** [comment]
> based on general TSC guidelines i have refrained from introducing additional optional resources as of now.

@maheshc01 first short on terminology: as ApplicationProfile is the resource, I suppose you are speaking about additional optional properties within the resource. And yes, I fully agree not to introduce these now. 

But I propose to design the API now so that additional properties can be added as needed in future without breaking the API (read: an API Client which only needs the network thresholds can still use also a future version without being aware that there are further properties available). 

Within the schema of ApplicationProfile that is ensured. Network thresholds are optional and you can add further optional properties without breaking the API.

But the create operation is currently not extensible. You have currently defined the body content as
{
   packetDelayBudget: {...}
   targetMinDownstreamRate: {...}
   ...
}
(BTW: none of the fields is mandatory, nor the body ... so you can have both cases: no body and empty body)

If you want to extend later with additional properties, you would have to push the networkQualityThresholds one level deeper (if you don't want to include them into networkQualityThresholds) - which is a breaking change.

For that reason my proposal is to define to define the body of the create operation from the beginning with an own schema, having networkQualityThresholds currently as the only (optional) property:
{
  networkQualityThresholds: {...}
}
which would allow to introduce further optional properties beside networkQualityThresholds without breaking the API for existing clients.
(here I would define the body structure as required, excluding the no body case. It still can be empty {} if no networkQualityThresholds are provided or can contain an empty networkQualityThresholds structure  - the API implementation has to handle these cases).

**Comment by maheshc01** [comment]
thank you for the feedback.

I have create a new object "ApplicationProfileRequest" which now has "NetworkQualityThresholds" as the only property under it. In future the ApplicationProfileRequest can be updated to introduce new properties like "ComputeRequirements", application life cycle management related properties etc.

I have also marked the NetworkQualityThresholds as required property. So users will have to have the object within  ApplicationProfileRequest but still have the flexibility to only define thresholds for the network KPIs that their application cares about.

fix is available in commit [7acdc0b](https://github.com/camaraproject/ConnectivityInsights/pull/67/commits/7acdc0b9cf5cfef21af872a00028198c778d3f92)
